apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eechart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: IN_BROKER_HOST
          value: {{ .Values.broker }}
        readinessProbe:
          exec:
            command:
            - netstat
            - -na
            - |
            - grep
            - "3306"
          initialDelaySeconds: 1
          periodSeconds: 1
